export const data = {
    amount: 6069,
    amountMin: 5050,
    amountNet: 5100,
    appliedPromotions: [],
    cancellationPolicy: {id: 14, name: "Economy cancellation policy", parameters: [{fee: 100, time: 1440}], rideType: "duration"},
    companyId: null,
    currency: "EUR",
    distance: null,
    duration: 1,
    estimatedArrivalTime: null,
    finalAmountGross: 6069,
    finalAmountMin: null,
    finalAmountNet: 5100,
    fixed: false,
    group: "Popular",
    isPreselected: true,
    isReturnRideAvailable: false,
    offerIdentifier: "offer_60acfd47d217d8.27848437_CDAN",
    onDemand: false,
    priceVary: false,
    provider: "rule_graph",
    reversed: false,
    sixtCustomerNumber: null,
    vat: 0.19,
    vehicleType: {
        airportFreeWaitingTime: 30,
        benefits: ["No hidden fees - parking and tolls included in the price"],
        brand: "SIXT rides",
        brandTermsAndConditions: null,
        category: "Car",
        class: "Budget",
        code: "CDAN",
        defaultFreeWaitingTime: 15,
        description: "Affordable ride service at a fixed price",
        id: 1,
        imageType: "black_car",
        images: {
            hdpi: "https://img.mydriver.com/image/upload/t_hdpi/v1551258292/cms_images/ckoifpnmw4fdnlydzqhk.png",
            mdpi: "https://img.mydriver.com/image/upload/t_mdpi/v1551258292/cms_images/ckoifpnmw4fdnlydzqhk.png",
            native: "https://img.mydriver.com/image/upload/v1551258292/cms_images/ckoifpnmw4fdnlydzqhk.png",
            web: "https://img.mydriver.com/image/upload/t_web/v1551258292/cms_images/ckoifpnmw4fdnlydzqhk.png",
            x1: "https://img.mydriver.com/image/upload/t_x1/v1551258292/cms_images/ckoifpnmw4fdnlydzqhk.png",
            x2: "https://img.mydriver.com/image/upload/t_x2/v1551258292/cms_images/ckoifpnmw4fdnlydzqhk.png",
            x3: "https://img.mydriver.com/image/upload/t_x3/v1551258292/cms_images/ckoifpnmw4fdnlydzqhk.png",
            xhdpi: "https://img.mydriver.com/image/upload/t_xhdpi/v1551258292/cms_images/ckoifpnmw4fdnlydzqhk.png",
            xxhdpi: "https://img.mydriver.com/image/upload/t_xxhdpi/v1551258292/cms_images/ckoifpnmw4fdnlydzqhk.png",
        },
        logo: {
            hdpi: "https://img.mydriver.com/image/upload/t_hdpi/v1549011723/logos/ride/Sixt_ride_2d_4c_pos.png",
            mdpi: "https://img.mydriver.com/image/upload/t_mdpi/v1549011723/logos/ride/Sixt_ride_2d_4c_pos.png",
            native: "https://img.mydriver.com/image/upload/v1549011723/logos/ride/Sixt_ride_2d_4c_pos.png",
            web: "https://img.mydriver.com/image/upload/t_web/v1549011723/logos/ride/Sixt_ride_2d_4c_pos.png",
            x1: "https://img.mydriver.com/image/upload/t_x1/v1549011723/logos/ride/Sixt_ride_2d_4c_pos.png",
            x2: "https://img.mydriver.com/image/upload/t_x2/v1549011723/logos/ride/Sixt_ride_2d_4c_pos.png",
            x3: "https://img.mydriver.com/image/upload/t_x3/v1549011723/logos/ride/Sixt_ride_2d_4c_pos.png",
            xhdpi: "https://img.mydriver.com/image/upload/t_xhdpi/v1549011723/logos/ride/Sixt_ride_2d_4c_pos.png",
            xxhdpi: "https://img.mydriver.com/image/upload/t_xxhdpi/v1549011723/logos/ride/Sixt_ride_2d_4c_pos.png",
        },
        marketingImages: [{
            hdpi: "https://img.mydriver.com/image/upload/t_hdpi/v1539269355/vehicle_type_marketing/eco_light.jpg",
            mdpi: "https://img.mydriver.com/image/upload/t_mdpi/v1539269355/vehicle_type_marketing/eco_light.jpg",
            native: "https://img.mydriver.com/image/upload/v1539269355/vehicle_type_marketing/eco_light.jpg",
            web: "https://img.mydriver.com/image/upload/t_web/v1539269355/vehicle_type_marketing/eco_light.jpg",
            x1: "https://img.mydriver.com/image/upload/t_x1/v1539269355/vehicle_type_marketing/eco_light.jpg",
            x2: "https://img.mydriver.com/image/upload/t_x2/v1539269355/vehicle_type_marketing/eco_light.jpg",
            x3: "https://img.mydriver.com/image/upload/t_x3/v1539269355/vehicle_type_marketing/eco_light.jpg",
            xhdpi: "https://img.mydriver.com/image/upload/t_xhdpi/v1539269355/vehicle_type_marketing/eco_light.jpg",
            xxhdpi: "https://img.mydriver.com/image/upload/t_xxhdpi/v1539269355/vehicle_type_marketing/eco_light.jpg",
        }],
        milesRedemption: false,
        mobileLogo: null,
        name: "ECONOMY_CLASS",
        nrOfBaggage: 2,
        nrOfPassengers: 2,
        onDemand: false,
        onDemandCapability: "Scheduled",
        priceVary: false,
        roamingType: "ride_hailing",
        title: "Economy Light",
    },
    voucherAmount: 0,
    voucherCode: null,
};